sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - git config --global user.name "LexBot"
  - git config --global user.email "jamie.mansfield.jm@outlook.com"
env:
  global:
    - LEX_DEPLOY=https://github.com/LexBot/Deploy.git DEPLOY_ROOT=/tmp/lex/deploy
    - secure: "PiG+K7el2c4ly92T9UZ+k4qJFzbDI+3IREWYwuMcy93S8vtGspyk0iImup/8iFNx6Fd/4SbNNnxyarOmvRfO8j9JKh9gXi2jr3EkS2gGr63CcYxTsdxkzWqoX5s8s3Qct0KAlV0HxSlvfIe5682QhyH3LLZrcFBu3258C+z2a34="
after_success:
  - git clone $LEX_DEPLOY $DEPLOY_ROOT && $DEPLOY_ROOT/maven_repo "mvn source:jar javadoc:jar deploy"
notifications:
  email: false
  irc:
    channels:
      - "irc.esper.net#jamierocks"
    on_success: change
    on_failure: always
