name: EnderBow
main: uk.jamierocks.bukkit.enderbow.EnderBowPlugin
version: 1.5.0
commands:
  enderbow:
    description: Give the caller an Ender Bow
    aliases:
      - eb
      - ebow
permissions:
  enderbow.*:
    description: Gives access to all EnderBow related commands
    children:
      enderbow.give: true
      enderbow.spawn: true
  enderbow.give:
    description: Give the caller an Ender Bow
    default: op
  enderbow.spawn:
    description: Give the caller an Ender Bow
    default: op
